In [22]:
import numpy as np

In [26]:
a = np.array([[1,2,3]])
print(a)
print(a.shape)

[[1 2 3]]
(1, 3)


In [25]:
b = np.random.rand(5)
print(b)
print(b.shape)

[0.41605511 0.27614368 0.43673446 0.47142782 0.44322443]
(5,)


In [27]:
c = np.random.rand(1,5)
print(c)
print(c.shape)

[[0.35477433 0.28379475 0.83714476 0.71693782 0.62720109]]
(1, 5)


In [31]:
#b.shape = 5,   -->  1,5
#d = b[np.newaxis,:]
#d = b[np.newaxis,:]
#b.shape = 5,   -->  5,1
d = b[:,np.newaxis]
print(d)
print(d.shape)

[[0.41605511]
 [0.27614368]
 [0.43673446]
 [0.47142782]
 [0.44322443]]
(5, 1)


In [34]:
b = np.random.rand(5).reshape((5,1))
print(b)
print(b.shape)

[[0.83641181]
 [0.34397506]
 [0.72776409]
 [0.93690321]
 [0.67516666]]
(5, 1)
